RUN apt-get update
RUN apt-get install -y python3-opencv
RUN pip install opencv-python
RUN apt-get install -y opencv-python-headless
RUN pip install opencv-python-headless
RUN apt-get install libgl1
RUN apt-get install ffmpeg libsm6 libxext6  -y
